version: "3"
services:
    nodeserver:
        build: "/root/sample"
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: "/root"
        container_name: "nginx"
        ports:
            - "80:80"
            - "443:443"
